# Generated by Django 3.2.9 on 2021-12-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
