# Generated by Django 3.2.9 on 2021-12-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_description',
            field=models.URLField(max_length=500),
        ),
    ]
